json.id                   @task.id
json.title                @task.title
json.description          @task.description
json.address              @task.address
json.completion_time      @task.completion_time
json.date_time            @task.date_time
json.status               @task.status
json.pinned               @task.pinned
json.priority_level       @task.priority_level